spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yupi?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: your_password_here
